import { mkdir, readFile, writeFile, copyFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import packageJson from "../package.json" with { type: "json" };
import { buildConceptWorker } from "./concept-worker-artifact.js";
import { buildSyntaxWorker } from "./syntax-worker-artifact.js";

const repository = resolve(import.meta.dirname, "..");
export const searchPluginRoot = join(repository, "plugins/baoer-signal-grep");
export const SEARCH_PLUGIN_FILES = [
  "LICENSE",
  "package.json",
  "omp-extension.mjs",
  "concept-worker.mjs",
  "syntax-worker.mjs",
  "syntax-worker.toml",
  ".codex-plugin/plugin.json",
  ".claude-plugin/plugin.json",
  ".codex.mcp.json",
  "mcp-server.mjs",
  ".mcp.json",
  "kimi.plugin.json",
  "hooks/hooks.json",
  "hooks/search-policy.mjs",
  "hooks/tree-sitter.wasm",
  "hooks/tree-sitter-bash.wasm",
  "hooks/tree-sitter-powershell.wasm",
  "hooks/THIRD_PARTY_NOTICES.txt",
];

export async function buildSearchPlugin(root: string): Promise<void> {
  const hooks = join(root, "hooks");
  await mkdir(hooks, { recursive: true });
  await copyFile(join(repository, "LICENSE"), join(root, "LICENSE"));
  const result = await Bun.build({
    entrypoints: [join(repository, "src/search-policy-hook.ts")],
    outdir: hooks,
    naming: "search-policy.mjs",
    root: repository,
    target: "node",
    format: "esm",
    sourcemap: "none",
  });
  if (!result.success) throw new AggregateError(result.logs, "Search policy hook build failed");
  const ompResult = await Bun.build({
    entrypoints: [join(repository, "src/omp-marketplace-entry.ts")],
    outdir: root,
    naming: "omp-extension.mjs",
    root: repository,
    target: "bun",
    format: "esm",
    banner:
      "/* @generated by scripts/build-search-plugin.ts; lint source modules instead. */\n/* biome-ignore-all lint -- generated bundle; lint source modules instead. */",
    sourcemap: "none",
  });
  if (!ompResult.success) throw new AggregateError(ompResult.logs, "OMP extension build failed");
  const ompBundle = join(root, "omp-extension.mjs");
  await writeFile(ompBundle, (await readFile(ompBundle, "utf8")).replace(/[ \t]+$/gmu, ""));
  await Promise.all([
    buildConceptWorker(root),
    buildSyntaxWorker(root),
    copyFile(join(repository, "src/syntax-worker.toml"), join(root, "syntax-worker.toml")),
  ]);
  const notices = await Promise.all(
    [
      ["web-tree-sitter", "tree-sitter.wasm"],
      ["tree-sitter-bash", "tree-sitter-bash.wasm"],
      ["tree-sitter-powershell", "tree-sitter-powershell.wasm"],
    ].map(async ([dependency, file]) => {
      if (!dependency || !file) throw new Error("Invalid search policy artifact dependency");
      const directory = join(repository, "node_modules", dependency);
      await copyFile(join(directory, file), join(hooks, file));
      return `${dependency}\n${await readFile(join(directory, "LICENSE"), "utf8")}`;
    }),
  );
  await writeFile(join(hooks, "THIRD_PARTY_NOTICES.txt"), notices.join("\n\n"));
  const identity = {
    name: "baoer-signal-grep",
    version: packageJson.version,
    description:
      "Require baoer_signal_grep for conventional local searches while keeping development tools available.",
    author: { name: packageJson.author },
    homepage: packageJson.homepage,
    license: packageJson.license,
  };
  const ompPackage = {
    name: "baoer-signal-grep",
    version: packageJson.version,
    private: true,
    type: "module",
    omp: { extensions: ["./omp-extension.mjs"] },
  };
  const mcpEnvironment = {
    npm_config_ignore_scripts: "true",
    ONNXRUNTIME_NODE_INSTALL_CUDA: "skip",
    BAOER_SIGNAL_GREP_MCP_OUTPUT_MODE: "model",
  };
  const localMcp = {
    baoer_signal_grep: {
      command: "node",
      args: ["./mcp-server.mjs", "--stdio"],
      cwd: "./",
      env: mcpEnvironment,
    },
  };
  const claudeMcp = {
    baoer_signal_grep: {
      command: "node",
      args: ["${CLAUDE_PLUGIN_ROOT}/mcp-server.mjs", "--stdio"],
      env: mcpEnvironment,
    },
  };
  const localMcpServer = [
    'const server = new URL("../../src/mcp-server.mjs", import.meta.url);',
    "await import(server.href);",
  ].join("\n");
  const files: Record<string, unknown> = {
    "package.json": ompPackage,
    ".codex-plugin/plugin.json": {
      ...identity,
      mcpServers: "./.codex.mcp.json",
      interface: {
        displayName: "baoer_signal_grep",
        shortDescription: "Enforced local code search",
        longDescription: identity.description,
        defaultPrompt: "Search this project's code using baoer_signal_grep.",
        developerName: packageJson.author,
        category: "Productivity",
        capabilities: [],
      },
    },
    ".claude-plugin/plugin.json": identity,
    ".codex.mcp.json": { mcpServers: localMcp },
    "mcp-server.mjs": localMcpServer,
    ".mcp.json": { mcpServers: claudeMcp },
    "hooks/hooks.json": {
      hooks: {
        PreToolUse: [
          {
            matcher:
              "^(?:Bash|bash|PowerShell|powershell|Shell|shell|shell_command|exec_command|Grep|grep|Glob|GlobFile|SearchFileContent|SearchFiles|find)$",
            hooks: [
              {
                type: "command",
                command: 'node "${CLAUDE_PLUGIN_ROOT}/hooks/search-policy.mjs"',
                timeout: 5,
              },
            ],
          },
        ],
      },
    },
    "kimi.plugin.json": {
      ...identity,
      mcpServers: localMcp,
      systemPrompt:
        "Use baoer_signal_grep for local content and filename searches. The plugin blocks conventional alternative search entries. Ordinary reads, edits, tests and builds remain available.",
      hooks: [
        {
          event: "PreToolUse",
          matcher: "^(?:Bash|Grep|Glob|Shell|SearchFileContent|SearchFiles|GlobFile)$",
          command: 'node "./hooks/search-policy.mjs"',
          timeout: 5,
        },
      ],
    },
  };
  await Promise.all(
    Object.entries(files).map(async ([path, content]) => {
      await mkdir(dirname(join(root, path)), { recursive: true });
      return writeFile(join(root, path), `${JSON.stringify(content, null, 2)}\n`);
    }),
  );
}
